from src.roulette_selection import roulette_selection
from src.contants import EXPLOTATION_PERCENTAGE


def test_roulette_selection():
    assert (
        len(
            roulette_selection(
                {
                    "A": [],
                    "B": [["Red", "Red", "Purple", "Cyan"]],
                    "C": [
                        ["Red", "Red", "Purple", "Green"],
                        ["Cyan", "Green", "Purple", "Red"],
                        ["Green", "Cyan", "Purple", "Purple"],
                    ],
                    "D": [
                        ["Green", "Purple", "Red", "Purple"],
                        ["Green", "Green", "Yellow", "Cyan"],
                        ["Red", "Purple", "Cyan", "Green"],
                        ["Green", "Orange", "Orange", "Cyan"],
                        ["Purple", "Cyan", "Purple", "Green"],
                        ["Green", "Purple", "Cyan", "Purple"],
                        ["Red", "Cyan", "Green", "Cyan"],
                        ["Green", "Yellow", "Purple", "Green"],
                        ["Green", "Purple", "Cyan", "Yellow"],
                        ["Orange", "Red", "Yellow", "Cyan"],
                        ["Red", "Red", "Purple", "Yellow"],
                        ["Yellow", "Red", "Cyan", "Cyan"],
                        ["Green", "Yellow", "Purple", "Green"],
                        ["Green", "Yellow", "Purple", "Green"],
                        ["Green", "Purple", "Purple", "Green"],
                        ["Yellow", "Orange", "Purple", "Cyan"],
                        ["Purple", "Red", "Cyan", "Orange"],
                        ["Yellow", "Cyan", "Purple", "Green"],
                        ["Yellow", "Orange", "Purple", "Cyan"],
                        ["Green", "Yellow", "Orange", "Cyan"],
                        ["Green", "Yellow", "Yellow", "Cyan"],
                        ["Green", "Yellow", "Purple", "Green"],
                        ["Purple", "Green", "Orange", "Cyan"],
                        ["Green", "Cyan", "Cyan", "Red"],
                        ["Green", "Cyan", "Cyan", "Red"],
                        ["Green", "Yellow", "Yellow", "Cyan"],
                        ["Green", "Purple", "Purple", "Green"],
                        ["Green", "Orange", "Red", "Purple"],
                        ["Purple", "Red", "Cyan", "Purple"],
                        ["Purple", "Green", "Orange", "Cyan"],
                        ["Yellow", "Cyan", "Purple", "Green"],
                        ["Purple", "Red", "Cyan", "Purple"],
                        ["Purple", "Red", "Purple", "Purple"],
                    ],
                    "E": [
                        ["Purple", "Cyan", "Cyan", "Green"],
                        ["Red", "Yellow", "Purple", "Purple"],
                        ["Green", "Cyan", "Cyan", "Yellow"],
                        ["Orange", "Red", "Green", "Orange"],
                        ["Red", "Cyan", "Cyan", "Green"],
                        ["Green", "Yellow", "Red", "Green"],
                        ["Yellow", "Cyan", "Red", "Green"],
                        ["Purple", "Green", "Purple", "Green"],
                        ["Green", "Purple", "Green", "Green"],
                        ["Green", "Yellow", "Cyan", "Green"],
                        ["Red", "Red", "Orange", "Purple"],
                        ["Green", "Yellow", "Cyan", "Green"],
                        ["Green", "Yellow", "Green", "Purple"],
                        ["Purple", "Red", "Orange", "Red"],
                        ["Green", "Yellow", "Cyan", "Green"],
                        ["Yellow", "Green", "Green", "Cyan"],
                        ["Cyan", "Cyan", "Purple", "Yellow"],
                        ["Green", "Purple", "Green", "Yellow"],
                        ["Orange", "Yellow", "Green", "Cyan"],
                        ["Orange", "Yellow", "Green", "Cyan"],
                        ["Purple", "Purple", "Orange", "Cyan"],
                        ["Green", "Cyan", "Orange", "Yellow"],
                        ["Green", "Purple", "Orange", "Yellow"],
                        ["Cyan", "Green", "Yellow", "Cyan"],
                        ["Purple", "Green", "Red", "Green"],
                        ["Green", "Cyan", "Orange", "Yellow"],
                        ["Cyan", "Orange", "Red", "Purple"],
                        ["Green", "Cyan", "Orange", "Yellow"],
                        ["Red", "Red", "Green", "Green"],
                        ["Orange", "Red", "Yellow", "Purple"],
                        ["Orange", "Yellow", "Green", "Cyan"],
                        ["Red", "Red", "Green", "Green"],
                        ["Green", "Cyan", "Orange", "Yellow"],
                        ["Yellow", "Green", "Cyan", "Purple"],
                        ["Purple", "Green", "Red", "Green"],
                        ["Cyan", "Orange", "Red", "Purple"],
                    ],
                    "F": [
                        ["Red", "Red", "Orange", "Yellow"],
                        ["Orange", "Red", "Orange", "Yellow"],
                        ["Cyan", "Yellow", "Orange", "Green"],
                        ["Yellow", "Cyan", "Orange", "Cyan"],
                        ["Yellow", "Green", "Red", "Yellow"],
                        ["Orange", "Yellow", "Green", "Purple"],
                        ["Red", "Yellow", "Green", "Green"],
                        ["Yellow", "Cyan", "Orange", "Green"],
                        ["Red", "Orange", "Green", "Orange"],
                        ["Yellow", "Cyan", "Cyan", "Cyan"],
                        ["Purple", "Purple", "Cyan", "Yellow"],
                        ["Cyan", "Cyan", "Green", "Orange"],
                        ["Purple", "Cyan", "Yellow", "Orange"],
                        ["Orange", "Cyan", "Cyan", "Green"],
                        ["Green", "Green", "Green", "Orange"],
                        ["Cyan", "Yellow", "Green", "Yellow"],
                    ],
                    "G": [
                        ["Purple", "Purple", "Orange", "Yellow"],
                        ["Yellow", "Yellow", "Cyan", "Orange"],
                        ["Purple", "Yellow", "Yellow", "Orange"],
                        ["Red", "Yellow", "Orange", "Yellow"],
                        ["Orange", "Green", "Green", "Green"],
                        ["Red", "Orange", "Red", "Orange"],
                        ["Yellow", "Orange", "Green", "Green"],
                        ["Purple", "Yellow", "Yellow", "Orange"],
                        ["Yellow", "Green", "Green", "Green"],
                        ["Red", "Orange", "Red", "Yellow"],
                    ],
                    "H": [["Yellow", "Orange", "Orange", "Yellow"]],
                }
            )
        )
        == EXPLOTATION_PERCENTAGE
    )
